### ISSUE TITLE
Some artisan commands do not take required input

### ISSUE THREAD

**Issue by dorkster100** [adalessa/laravel.nvim#13]
When trying to run some of the artisan commands that require input the terminal is not letting pass any input.
For example when running `php artisan enforce:query` I am not able to write `yes` or even insert `<cr>`

**Comment by dorkster100** [comment]
What is the benefit of the `buffer` runner over the `terminal`, if we set terminal to be runner for this command it works properly?

**Comment by adalessa** [comment]
Yes the command will not be interactive unless you use `terminal` runner.
The buffer is useful to control the job state. Because I can interact with the job id, stop it, send information grammatically.
Is for sure not for all, but I found that is best for most. You can change your default to terminal `default_runner = "buffer",` to terminal. I will consider the possibility to change it if more people think is the best for a general use.

**Comment by dorkster100** [comment]
Can you please explain a bit how you do these things, especially about the last one

**Comment by adalessa** [comment]
For the watch which is base on the buffer It need to redraw the information, re-trigger it. this is done using the same buffer. With buffer I can clean it completly and re-write it completely.

**Comment by dorkster100** [comment]
But `watch` can still use the `buffer` base, what I actually mean is to use the `terminal` runner for the `artisan` commands.

**Comment by adalessa** [comment]
I see you point, is more usefull to have it as terminal by default. I will do it
