### ISSUE TITLE
Laravel artisan command does not open telescope first time it is run

### ISSUE THREAD

**Issue by dorkster100** [adalessa/laravel.nvim#68]
If i open new nvim instance and then open the project, first time i run `Laravel artisan` nothing happens, all further calls work fine.

**Comment by adalessa** [comment]
this command maps to `require("telescope").extensions.laravel.commands` so I think the only problem could be that the extension is not fully loaded the first time in telescope. Are you using lazy ? 
I think it could help replace instead of calling the extension calling directly. 
`require('laravel.telescope.pickers.commands')`

**Comment by dorkster100** [comment]
yes, I am, this did not help, I will try to debug a bit more later
