### ISSUE TITLE
Failed to run config for laravel.nvim - attempt to call method 'executable' (a nil value)

### ISSUE THREAD

**Issue by Kazuto** [adalessa/laravel.nvim#73]
Upon entering a laravel project I now get the following error, though it worked before my vacation:

![image](https://github.com/adalessa/laravel.nvim/assets/25435034/51abce6a-0177-4b07-a5ac-df445fe0a2fc)

This is my configuration
```lua
local laravel = {
	"adalessa/laravel.nvim",
	dependencies = {
		"nvim-telescope/telescope.nvim",
		"tpope/vim-dotenv",
		"MunifTanjim/nui.nvim",
		"nvimtools/none-ls.nvim",
	},
	cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
	keys = {
		{ "<leader>la", ":Laravel artisan<cr>" },
		{ "<leader>lr", ":Laravel routes<cr>" },
		{ "<leader>lm", ":Laravel related<cr>" },
		{
			"<leader>lt",
			function()
				require("laravel.tinker").send_to_tinker()
			end,
			mode = "v",
			desc = "Laravel Application Routes",
		},
	},
	event = { "VeryLazy" },
	config = function()
		require("laravel").setup() -- Line 251
		require("telescope").load_extension("laravel")
	end,
}
```

And my `.zshrc` contains

```bash
export NVIM_LARAVEL_ENV=local
```

**Comment by adalessa** [comment]
This for sure puzzles me. Since in the code before calling the executable there is a check for nil. Are you still in v1 or have you updated.  I assume you have updated since I the lines matches the last version.
If you run again after loading `require('laravel').setup()` does it return the same error ?

If still happen, could you do a `vim.print(M.environment)` on the file `laravel/environment/init.lua` on line 63?
Tyring to understand what is assigning if is not null but also does not have the expected function.

**Comment by adalessa** [comment]
Closing it for now due to inactivity. If you think this is still an issue please re-open with details.
